/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MealDaySlot {
        /**
          * @default ''
         */
        "dayName": string;
        /**
          * @default true
         */
        "isEmpty": boolean;
        /**
          * @default ''
         */
        "mealType": string;
        /**
          * @default ''
         */
        "recipeId": string;
        /**
          * @default ''
         */
        "recipeImage": string;
        /**
          * @default ''
         */
        "recipeName": string;
    }
    interface RecipeCard {
        /**
          * @default false
         */
        "compact": boolean;
        /**
          * @default false
         */
        "isFavorite": boolean;
        /**
          * @default ''
         */
        "recipeArea": string;
        /**
          * @default ''
         */
        "recipeCategory": string;
        /**
          * @default ''
         */
        "recipeId": string;
        /**
          * @default ''
         */
        "recipeImage": string;
        /**
          * @default ''
         */
        "recipeTitle": string;
    }
    interface RecipeSearch {
        /**
          * @default '[]'
         */
        "areas": string;
        /**
          * @default '[]'
         */
        "categories": string;
        /**
          * @default 'Search recipes...'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "selectedArea": string;
        /**
          * @default ''
         */
        "selectedCategory": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface StarRating {
        /**
          * @default 5
         */
        "maxStars": number;
        /**
          * @default 0
         */
        "rating": number;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default 'md'
         */
        "size": string;
    }
    interface TagBadge {
        /**
          * @default false
         */
        "clickable": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default false
         */
        "removable": boolean;
        /**
          * @default 'default'
         */
        "variant": string;
    }
}
export interface MealDaySlotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMealDaySlotElement;
}
export interface RecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeCardElement;
}
export interface RecipeSearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeSearchElement;
}
export interface StarRatingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStarRatingElement;
}
export interface TagBadgeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTagBadgeElement;
}
declare global {
    interface HTMLMealDaySlotElementEventMap {
        "mealRemoved": { day: string; mealType: string };
        "slotClicked": { day: string; mealType: string };
    }
    interface HTMLMealDaySlotElement extends Components.MealDaySlot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMealDaySlotElementEventMap>(type: K, listener: (this: HTMLMealDaySlotElement, ev: MealDaySlotCustomEvent<HTMLMealDaySlotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMealDaySlotElementEventMap>(type: K, listener: (this: HTMLMealDaySlotElement, ev: MealDaySlotCustomEvent<HTMLMealDaySlotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMealDaySlotElement: {
        prototype: HTMLMealDaySlotElement;
        new (): HTMLMealDaySlotElement;
    };
    interface HTMLRecipeCardElementEventMap {
        "favoriteToggled": { id: string; isFavorite: boolean };
        "cardClicked": { id: string };
    }
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLRecipeSearchElementEventMap {
        "searchChanged": string;
        "categoryChanged": string;
        "areaChanged": string;
        "searchSubmitted": string;
    }
    interface HTMLRecipeSearchElement extends Components.RecipeSearch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeSearchElementEventMap>(type: K, listener: (this: HTMLRecipeSearchElement, ev: RecipeSearchCustomEvent<HTMLRecipeSearchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeSearchElementEventMap>(type: K, listener: (this: HTMLRecipeSearchElement, ev: RecipeSearchCustomEvent<HTMLRecipeSearchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeSearchElement: {
        prototype: HTMLRecipeSearchElement;
        new (): HTMLRecipeSearchElement;
    };
    interface HTMLStarRatingElementEventMap {
        "ratingChanged": number;
    }
    interface HTMLStarRatingElement extends Components.StarRating, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStarRatingElementEventMap>(type: K, listener: (this: HTMLStarRatingElement, ev: StarRatingCustomEvent<HTMLStarRatingElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStarRatingElementEventMap>(type: K, listener: (this: HTMLStarRatingElement, ev: StarRatingCustomEvent<HTMLStarRatingElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStarRatingElement: {
        prototype: HTMLStarRatingElement;
        new (): HTMLStarRatingElement;
    };
    interface HTMLTagBadgeElementEventMap {
        "badgeRemoved": string;
        "badgeClicked": string;
    }
    interface HTMLTagBadgeElement extends Components.TagBadge, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTagBadgeElementEventMap>(type: K, listener: (this: HTMLTagBadgeElement, ev: TagBadgeCustomEvent<HTMLTagBadgeElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTagBadgeElementEventMap>(type: K, listener: (this: HTMLTagBadgeElement, ev: TagBadgeCustomEvent<HTMLTagBadgeElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTagBadgeElement: {
        prototype: HTMLTagBadgeElement;
        new (): HTMLTagBadgeElement;
    };
    interface HTMLElementTagNameMap {
        "meal-day-slot": HTMLMealDaySlotElement;
        "recipe-card": HTMLRecipeCardElement;
        "recipe-search": HTMLRecipeSearchElement;
        "star-rating": HTMLStarRatingElement;
        "tag-badge": HTMLTagBadgeElement;
    }
}
declare namespace LocalJSX {
    interface MealDaySlot {
        /**
          * @default ''
         */
        "dayName"?: string;
        /**
          * @default true
         */
        "isEmpty"?: boolean;
        /**
          * @default ''
         */
        "mealType"?: string;
        "onMealRemoved"?: (event: MealDaySlotCustomEvent<{ day: string; mealType: string }>) => void;
        "onSlotClicked"?: (event: MealDaySlotCustomEvent<{ day: string; mealType: string }>) => void;
        /**
          * @default ''
         */
        "recipeId"?: string;
        /**
          * @default ''
         */
        "recipeImage"?: string;
        /**
          * @default ''
         */
        "recipeName"?: string;
    }
    interface RecipeCard {
        /**
          * @default false
         */
        "compact"?: boolean;
        /**
          * @default false
         */
        "isFavorite"?: boolean;
        "onCardClicked"?: (event: RecipeCardCustomEvent<{ id: string }>) => void;
        "onFavoriteToggled"?: (event: RecipeCardCustomEvent<{ id: string; isFavorite: boolean }>) => void;
        /**
          * @default ''
         */
        "recipeArea"?: string;
        /**
          * @default ''
         */
        "recipeCategory"?: string;
        /**
          * @default ''
         */
        "recipeId"?: string;
        /**
          * @default ''
         */
        "recipeImage"?: string;
        /**
          * @default ''
         */
        "recipeTitle"?: string;
    }
    interface RecipeSearch {
        /**
          * @default '[]'
         */
        "areas"?: string;
        /**
          * @default '[]'
         */
        "categories"?: string;
        "onAreaChanged"?: (event: RecipeSearchCustomEvent<string>) => void;
        "onCategoryChanged"?: (event: RecipeSearchCustomEvent<string>) => void;
        "onSearchChanged"?: (event: RecipeSearchCustomEvent<string>) => void;
        "onSearchSubmitted"?: (event: RecipeSearchCustomEvent<string>) => void;
        /**
          * @default 'Search recipes...'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "selectedArea"?: string;
        /**
          * @default ''
         */
        "selectedCategory"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface StarRating {
        /**
          * @default 5
         */
        "maxStars"?: number;
        "onRatingChanged"?: (event: StarRatingCustomEvent<number>) => void;
        /**
          * @default 0
         */
        "rating"?: number;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: string;
    }
    interface TagBadge {
        /**
          * @default false
         */
        "clickable"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        "onBadgeClicked"?: (event: TagBadgeCustomEvent<string>) => void;
        "onBadgeRemoved"?: (event: TagBadgeCustomEvent<string>) => void;
        /**
          * @default false
         */
        "removable"?: boolean;
        /**
          * @default 'default'
         */
        "variant"?: string;
    }

    interface MealDaySlotAttributes {
        "dayName": string;
        "mealType": string;
        "recipeName": string;
        "recipeImage": string;
        "recipeId": string;
        "isEmpty": boolean;
    }
    interface RecipeCardAttributes {
        "recipeId": string;
        "recipeTitle": string;
        "recipeImage": string;
        "recipeCategory": string;
        "recipeArea": string;
        "isFavorite": boolean;
        "compact": boolean;
    }
    interface RecipeSearchAttributes {
        "placeholder": string;
        "value": string;
        "categories": string;
        "areas": string;
        "selectedCategory": string;
        "selectedArea": string;
    }
    interface StarRatingAttributes {
        "rating": number;
        "maxStars": number;
        "readonly": boolean;
        "size": string;
    }
    interface TagBadgeAttributes {
        "label": string;
        "variant": string;
        "removable": boolean;
        "clickable": boolean;
    }

    interface IntrinsicElements {
        "meal-day-slot": Omit<MealDaySlot, keyof MealDaySlotAttributes> & { [K in keyof MealDaySlot & keyof MealDaySlotAttributes]?: MealDaySlot[K] } & { [K in keyof MealDaySlot & keyof MealDaySlotAttributes as `attr:${K}`]?: MealDaySlotAttributes[K] } & { [K in keyof MealDaySlot & keyof MealDaySlotAttributes as `prop:${K}`]?: MealDaySlot[K] };
        "recipe-card": Omit<RecipeCard, keyof RecipeCardAttributes> & { [K in keyof RecipeCard & keyof RecipeCardAttributes]?: RecipeCard[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `attr:${K}`]?: RecipeCardAttributes[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `prop:${K}`]?: RecipeCard[K] };
        "recipe-search": Omit<RecipeSearch, keyof RecipeSearchAttributes> & { [K in keyof RecipeSearch & keyof RecipeSearchAttributes]?: RecipeSearch[K] } & { [K in keyof RecipeSearch & keyof RecipeSearchAttributes as `attr:${K}`]?: RecipeSearchAttributes[K] } & { [K in keyof RecipeSearch & keyof RecipeSearchAttributes as `prop:${K}`]?: RecipeSearch[K] };
        "star-rating": Omit<StarRating, keyof StarRatingAttributes> & { [K in keyof StarRating & keyof StarRatingAttributes]?: StarRating[K] } & { [K in keyof StarRating & keyof StarRatingAttributes as `attr:${K}`]?: StarRatingAttributes[K] } & { [K in keyof StarRating & keyof StarRatingAttributes as `prop:${K}`]?: StarRating[K] };
        "tag-badge": Omit<TagBadge, keyof TagBadgeAttributes> & { [K in keyof TagBadge & keyof TagBadgeAttributes]?: TagBadge[K] } & { [K in keyof TagBadge & keyof TagBadgeAttributes as `attr:${K}`]?: TagBadgeAttributes[K] } & { [K in keyof TagBadge & keyof TagBadgeAttributes as `prop:${K}`]?: TagBadge[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "meal-day-slot": LocalJSX.IntrinsicElements["meal-day-slot"] & JSXBase.HTMLAttributes<HTMLMealDaySlotElement>;
            "recipe-card": LocalJSX.IntrinsicElements["recipe-card"] & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
            "recipe-search": LocalJSX.IntrinsicElements["recipe-search"] & JSXBase.HTMLAttributes<HTMLRecipeSearchElement>;
            "star-rating": LocalJSX.IntrinsicElements["star-rating"] & JSXBase.HTMLAttributes<HTMLStarRatingElement>;
            "tag-badge": LocalJSX.IntrinsicElements["tag-badge"] & JSXBase.HTMLAttributes<HTMLTagBadgeElement>;
        }
    }
}
